"use client"

// DO NOT EDIT THIS FILE !!!!!
import { useEffect } from "react"

const EXO = "exo"

interface AppProps {
  exercice?: () => void
}

export const App: React.FC<AppProps> = ({ exercice }) => {
  useEffect(() => {
    if (exercice) {
      exercice()
    }
  }, [exercice])

  return <div id={EXO}></div>
}

export const init = (label = "Exercice") => {
  if (!document) return console.error("document not found")

  const el = document.getElementById(EXO)
  if (el) {
    document.getElementById(EXO)?.parentNode?.removeChild(el)
  }
  let rootDiv = document.getElementById("root")

  if (!rootDiv) return console.error("root element not found")

  const exoDiv = document.createElement("div")
  const h2 = document.createElement("h2")
  h2.innerText = label
  exoDiv.setAttribute("id", EXO)
  exoDiv.appendChild(h2)
  rootDiv.appendChild(exoDiv)
}

const displayText = (label: string = "") => {
  const exoDiv = document.getElementById(EXO)
  const p = document.createElement("p")
  p.innerText = label

  if (!exoDiv) return console.error("exoDiv not found")

  exoDiv.appendChild(p)
}
export default displayText

export const initExo1 = (label = "formExo") => {
  init()
  const exoDiv = document.getElementById(EXO)

  if (!exoDiv) return console.error("exoDiv element not found")
  const form = document.createElement("form")
  form.setAttribute("id", label)
  const input = document.createElement("input")
  input.setAttribute("type", "text")
  // const button = document.createElement('input')
  // button.setAttribute('type', 'submit')
  // button.value = 'envoyer'
  form.appendChild(input)
  // form.appendChild(button)
  exoDiv.appendChild(form)
}

export const initExo2 = (label = "formExo") => {
  init()
  const exoDiv = document.getElementById(EXO)
  if (!exoDiv) return console.error("exoDiv element not found")
  const form = document.createElement("form")
  form.setAttribute("id", label)
  const input = document.createElement("input")
  input.setAttribute("type", "text")

  const button = document.createElement("input")
  button.setAttribute("type", "submit")
  button.value = "envoyer"
  form.appendChild(input)
  form.appendChild(button)
  exoDiv.appendChild(form)
}

export const initExo4 = (label = "formExo") => {
  init()
  const exoDiv = document.getElementById(EXO)
  if (!exoDiv) return console.error("exoDiv element not found")
  const form = document.createElement("form")
  form.setAttribute("id", label)

  const _label = document.createElement("label")
  _label.innerText = "HTML"
  _label.setAttribute("for", "html")

  const html = document.createElement("input")
  html.setAttribute("type", "radio")
  html.setAttribute("id", "html")
  html.setAttribute("value", "HTML")
  html.setAttribute("name", "language")

  const _labelcb = document.createElement("label")
  _labelcb.innerText = "CSS"
  _labelcb.setAttribute("for", "css")
  const css = document.createElement("input")
  css.setAttribute("type", "radio")
  css.setAttribute("id", "css")
  css.setAttribute("value", "CSS")
  css.setAttribute("name", "language")

  const _labeljs = document.createElement("label")
  _labeljs.innerText = "JS"
  _labeljs.setAttribute("for", "js")
  const js = document.createElement("input")
  js.setAttribute("type", "radio")
  js.setAttribute("id", "js")
  js.setAttribute("value", "JS")
  js.setAttribute("name", "language")

  const br = document.createElement("br")
  const button = document.createElement("input")
  button.setAttribute("type", "submit")
  button.value = "envoyer"

  form.appendChild(html)
  form.appendChild(_label)

  form.appendChild(css)
  form.appendChild(_labelcb)

  form.appendChild(js)
  form.appendChild(_labeljs)

  form.appendChild(br)
  form.appendChild(button)
  exoDiv.appendChild(form)
}
