"use client"

//DO NOT EDIT THIS FILE !!!!!
import { useEffect } from "react"

const EXO = "exo"

export const App = ({ exercice }) => {
  useEffect(() => {
    if (exercice) {
      exercice()
    }
  }, [exercice])
}
export const init = (label = "Final") => {
  const el = document.getElementById(EXO)
  if (el) {
    document.getElementById(EXO).parentNode.removeChild(el)
  }
  let rootDiv = document.getElementById("root")

  const exoDiv = document.createElement("div")
  const h2 = document.createElement("h2")
  h2.innerText = label
  exoDiv.setAttribute("id", EXO)
  exoDiv.appendChild(h2)
  rootDiv.appendChild(exoDiv)
}

const displayText = (label) => {
  const exoDiv = document.getElementById(EXO)
  const p = document.createElement("p")
  p.innerText = label
  exoDiv.appendChild(p)
}
export default displayText
