name: installation
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  setup:
    # ignore all-contributors
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run installation script
        run: npm run init
